### PR TITLE
Add "cmdasync" snippet

### PR DESCRIPTION
**Pull request by mgj**

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks you for the PR, but I wish you would have submitted an issue to discuss this before taking the time to submit this PR.  First, the declaration and conventions of the command does not align with the existing cmd snippet.  Also, adding the async/await in the ctor does not make the command async.  This can be misleading.  Commands are not async, and async/void Execute methods are acceptable.

**Comment by mgj** [comment]
Im sorry i didnt see a "contribution" file for this project so i figured i'd just submit a PR. Ill make sure to make an issue in the future

No worries, I just didnt like the "cmd" snippet because it references methods and properties that it itself doesnt generate so i made this because im too lazy to create the method and canExecute property every time

**Comment by brianlagunas** [comment]
It doesn't create the methods because we can't make assumptions about which methods you want.  It is easy to simply delete the CanExecute, and use the ctrl+. feature of VS to automatically create the methods.  We also can't assume that the use of ObvservesCanExcute should be standard.

**Comment by brianlagunas** [comment]
Also, the contributing doc is in the main repro: https://github.com/PrismLibrary/Prism/blob/master/.github/CONTRIBUTING.md.  I'll be sure to copy it over.  Thanks for bringing that to my attention.

**Pull request closed without merging**
